version: '3.4'

services:
  presentationlayer:
    image: ${DOCKER_REGISTRY-}testfault
    build:
      context: .
      dockerfile: src/PresentationLayer/Dockerfile
    environment:
      - ROOT_PATH=/app/wwwroot
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - postgres
      - seq

  postgres:
    image: postgres:14.1-alpine
    container_name: testfault-postgres
    
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '12345:5432'
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data

  seq:
    image: datalust/seq:latest
    container_name: testfault-seq
    ports:
      - 80:80
      - 5341:5341
    environment:
      ACCEPT_EULA: Y
